### ISSUE TITLE
Пофиксить картинку базы данных, загрузить заново

### ISSUE THREAD

**Issue by sheepsupremacy** [python-am-cp/E-Learning#18]

**Comment by vladanills** [comment]
https://pp.userapi.com/c844721/v844721800/1e47d1/0WMq3ciipvU.jpg

**Comment by vladanills** [comment]
Добавила картинку. Нужно потом еще доделать. На первое время хватит.

**Comment by snejanochka** [comment]
Пофиксить картинку в соответствии с добавленным описанием и/или изменить описание

**Comment by vladanills** [comment]
https://pp.userapi.com/c847120/v847120517/1d3da2/tuFE-j8F3z8.jpg
